### ISSUE TITLE
New Minio server have problem with big files

### ISSUE THREAD

**Issue by florianfrictus** [csia-pme/csia-pme#41]
![image](https://user-images.githubusercontent.com/58698728/208320362-8090c181-00d1-438d-910a-4b142bed627e.png)
New Minio

![image](https://user-images.githubusercontent.com/58698728/208320388-bceda271-b46c-4626-8608-6791828ccf7c.png)
Old Minio

test is 20MiB and test2 is 2B this problem cause an error when using dvc pull 
![image](https://user-images.githubusercontent.com/58698728/208320544-9b1f8ec5-a590-490a-9ef0-51595306df39.png)

dvc pull work with old minio

**Comment by florianfrictus** [comment]
There is maybe a problem with the minio server configuration blocking big files.

**Comment by ludelafo** [comment]
We'll stick to the MinIO server that was set up by the HEIA-FR as they already manage all the backups and the maintainance.

I'll update the services today to make sure all of them use the right MinIO server.
