### ISSUE TITLE
Publish official specification for client services in v1.0

### ISSUE THREAD

**Issue by sebastienrumley** [csia-pme/csia-pme#45]
As discussed with @PxReaz last week, we have to publish a very well defined specification describing what is expected from a service that can be registered by our engine.

This specification should consist of :
- A couple of sequence diagrams summarizing the process of subscribing, as well as sending a task to the service
- A couple of state diagrams describing the status of 
  - A task within a service
  - The service itself
- JSON snippets helping one to understand the format of the messages exchanged.

This doc should be sufficient to build a service and have it registering itself to an engine.

**Comment by aptrc** [comment]
Reference for the spec: https://csia-pme.github.io/csia-pme/reference/service/
