### ISSUE TITLE
Decide and implement file expiration time on S3

### ISSUE THREAD

**Issue by PxReaz** [csia-pme/csia-pme#46]
Need to define the amount of days/months that a file is kept on the S3 server and then implement the changes in the Storage

**Comment by ludelafo** [comment]
The expiration time is directly managed by MinIO with the help of a Lifecycle Rule.

The documentation to enable this is here: https://csia-pme.github.io/csia-pme/how-to-guides/how-to-set-expiration-time-on-bucket-files-with-minio/
