### ISSUE TITLE
Move Python dependencies from pip to Poetry

### ISSUE THREAD

**Issue by aptrc** [csia-pme/csia-pme#95]
Some packages dependencies updates caused the system to stop working.
To prevent this problem to occur in the future we are going to migrate from pip to Poetry as dependencies manager.

**Comment by ludelafo** [comment]
As mentioned in the PR:

"The Python ecosystem to manage dependencies all have trade-offs.

Poetry is a nice and clean solution that covers most of the issues pip faces. However, it fails at the moment with projects using Torch. https://github.com/python-poetry/poetry/issues/6409 exist but none seems to satisfy our use-case.

After a lot of errors and trials, Poetry cannot guarantee to work in every environment. If you have the chance to be able to use it, go for it.

In our case, to stay consistent with all services and after many considerations, it was decided to return to a simple pip solution.

This PR is closed for future reference."
